### PR TITLE
add server-models branch for schema

### PR DESCRIPTION
**Pull request by HammamAbuShehadeh**
#8 add new schema models

### CODE REVIEW

**Comment by AHMADJUAM** [comment]
please update the schema models files :)

**Comment by HammamAbuShehadeh** [comment]
> please update the schema models files :)

okay I will do it now just a second

**Comment by AHMADJUAM** [comment]
> > please update the schema models files :)
> 
> okay I will do it now just a second

thank you

**Comment by HammamAbuShehadeh** [comment]
Done Update scheme models files

**Comment by AHMADJUAM** [comment]
you are approved to merge it in develop-server.

**Pull request merged**
